HISTORY.md, demo/px-map-popup-info-demo.html, package-lock.json, package.json, px-map-behavior-popup.es6.js, test/px-map-popup-fixture.html, test/px-map-popup-tests.js
- Add `max-width` (default 400), `min-width` (default 300) properties to `px-map-popup-info` and `px-map-popup-data`
- Add unit test for the max/minWidth property
- Add `web-component-tester` to `devDependencies`, because we want all developers to keep the same version of testing driver
=> UI-1161 Make popup min/maxWidth configurable

demo/px-map-popup-data-demo.html, px-map-behavior-popup.es6.js
Fix min/maxWidth of data pupup
=> Fix popup-data bug

bower.json, demo/px-map-marker-group-demo.html, demo/px-map-popup-info-demo.html, package-lock.json, package.json, px-map-behavior-popup.es6.js
- Add `margin`attribute to popup data and popup info
- Add example to demo
- Add example to marker group demo
=> UI-2352 Add margin to popup container

HISTORY.md, bower.json, package.json, px-map-behavior-layer-geojson.es6.js
=> Ui 2179 route highlight

HISTORY.md, bower.json, package.json, px-map-behavior-layer-geojson.es6.js
Send the latlong data.
only 1 line code was changes, the rest is my lingt style update
=> UI-2367 - Pass Latlong data out

demo/px-map-marker-custom-demo.html, px-map-behavior-layer-geojson.es6.js
Scenario:
When there are multiple routes, if one route is a visited route and has a different color, on click on the visited route , then click on another route, the visited route defaulted to blue. 
This PR fixes that issue that was from our end. 
More details here 
https://servicemax.atlassian.net/browse/UI-2457
=> Ui 2457 bug visited route

HISTORY.md, bower.json, examples/marker-clusters-with-popups.html, package.json, px-map-behavior-marker-group.es6.js
- Provide ability to toggle the pop up
- Set `opened` property to null to close all popups.
=> UI-2451: Provide ability to toggle the pop up

HISTORY.md, bower.json, examples/layer-geojson-close-popup.html, package.json, px-map-behavior-layer-geojson.es6.js
- Fix for px-map-layer-geojson need to close the pop-ups when data changes.
=> UI-2633: Fix px-map-layer-geojson close popup when data changes

px-map-behavior-marker-group.es6.js
- Fix: Toggle Pop Over use case as detailed in UI-2876
- Example URL to Test px-map Local build: http://localhost:8080/examples/marker-clusters-with-popups.html
=> UI-2876: Toggle Pop Over use case

HISTORY.md, bower.json, package.json, px-map-behavior-marker-group.es6.js
- Toggle Pop Over use case-2.
- This should address all use cases necessary to closure of MAX-9593.
- Look out for ui-components-predix PR after this PR merge.
=> UI-2876: Toggle Pop Over use case-2

HISTORY.md, bower.json, examples/layer-geojson-custom-popup.html, package.json, px-map-behavior-layer-geojson.es6.js
- Support highlight and un-highlight routes with `multiple px-map-layer-geojson`.
=> UI-2961: Support highlight and unhighlight routes with multiple px-map-layer-geojson

HISTORY.md, bower.json, package.json, px-map-behavior-layer-geojson.es6.js
We want to center the popup according to it’s geocode.
=> MAX-10855: return popup's geocode when open it

HISTORY.md, bower.json, package-lock.json, package.json, sass/_map-icon-symbol.scss
- Update map marker icon size
- Release version 3.19.1
=> MAX-11226 - Update marker icon size

HISTORY.md, bower.json, package-lock.json, package.json
Update leaflet.markercluster version by using github tag.
=> MAX-24330 Update leaflet.markercluster version

HISTORY.md, bower.json, package-lock.json, package.json, px-map-behavior-layer-geojson.es6.js
@mallik-svmx @leslieli 
Please help review. Thanks.
=> MAX-25019 Return route segment info when click on it

HISTORY.md, px-map-behavior-layer-geojson.es6.js
@mallik-svmx @leslieli
Please help review. Thanks.
=> MAX-25019 Make the highlight control configurable in the data parameter

HISTORY.md, bower.json, package.json, px-map-behavior-layer-geojson.es6.js
Changes: add mouse over and mouse out events for px-map-layer-geojson element.
@elvinfucom @shinxi @leslieli @mallik-svmx 
Please help review, thanks!
=> MAX-25451 Show a tooltip when mouse over the route

HISTORY.md, bower.json, package.json, px-map-behavior-layer-geojson.es6.js
Changes:
- Filter the custom property "selectedStyle" to not display it in a popup for MAX-25774.
- Bypass the click event on highlight feature for MAX-25776.
@elvinfucom @shinxi @leslieli @mallik-svmx
Please help review, thanks!
=> MAX-25774/MAX-25776 Fix Bugs

HISTORY.md, bower.json, package.json
* Restrict leaflet to 1.7.1 to fix build issue.
@elvinfucom @leslieli @StanleyShen pls help review.
=> MAX-26537 SB is broken

HISTORY.md, bower.json, demo/px-map-demo.html, package.json, px-map-behavior-root.es6.js
Enhancement:
* Refactor the drawing tool.
* Add custom Finish button.
* Make sure only the layers drawn by drawing tool are editable.
* Support clean the drawn layers from outside of Map component.
=> MAX-26521: Enhance the drawing tools.

HISTORY.md, bower.json, package.json, px-map-behavior-root.es6.js
Bug Fix:
* Make sure PM is initialized before using it.
* Convert the circle layer to polygon layer otherwise it cannot be used as a polygon area.
=> MAX-26521: Fix drawing tools' bugs.

HISTORY.md, bower.json, package.json, px-map-behavior-root.es6.js
https://servicemax.atlassian.net/browse/MAX-26779
=> MAX-26779: PS via Map Panel loose end issues.

HISTORY.md, bower.json, demo/px-map-demo.html, package.json, px-map-behavior-root.es6.js
https://servicemax.atlassian.net/browse/MAX-26939
Enhancement:
* Add new function `_toggleShapeBtnsEnableState` to enable/disable the shape creation buttons.
* Enhance the logic of `_handleShapeLayerDrawEnd`.
=> MAX-26939: Apply the new design for the menus on polygon tool
